services:
  bd:
    image: "mcr.microsoft.com/mssql/server"
    container_name: bd_clientes
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=UPT.2024
    volumes:
      - ./db:/var/opt/mssql/data
  api:
    build: .
    container_name: api_clientes
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__ClienteDB=Server=bd_clientes;Database=BD_CLIENTES;User Id=admin_user;Password=UPT.2024;TrustServerCertificate=true
    depends_on:
      - bd
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./metrics/grafana_ds:/etc/grafana/provisioning/datasources
      - ./metrics/grafana_db:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
