name: Construir y Publicar Imagen

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Construir el proyecto
        run: dotnet build --configuration Release

      - name: Publicar el proyecto
        run: dotnet publish --configuration Release --output ./publish

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  

      - name: Construir imagen de Docker
        run: |
          docker build -t jf202107309/lab03_bd-ii_prometheus:latest .
          docker push jf202107309/lab03_bd-ii_prometheus:latest
