name: Delivery Workflow

on:
  workflow_dispatch:  # Este evento permite ejecutar el flujo de trabajo manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker images
        run: |
          docker pull jf202107309/lab03_bd-ii_prometheus:latest

      - name: Clean up any existing Prometheus containers
        run: |
          if [ "$(docker ps -aq -f name=prometheus)" ]; then
            docker stop prometheus
            docker rm prometheus
          fi

      - name: Run Prometheus container
        run: |
          docker run -d --name prometheus -p 9091:9090 jf202107309/lab03_bd-ii_prometheus:latest

      - name: Verify if Prometheus container is running
        run: |
          docker ps | grep prometheus || echo "Prometheus container is not running"

      - name: Wait for Prometheus to be ready
        run: |
          sleep 10  # Espera unos segundos para asegurarte de que Prometheus esté completamente iniciado

      - name: Check Prometheus status
        run: |
          until curl -s http://localhost:9091/-/healthy; do
            echo "Waiting for Prometheus to be healthy..."
            sleep 2
          done

      - name: Check Prometheus logs
        run: |
          docker logs prometheus

      - name: Make GET request to Prometheus
        run: |
          curl -G http://localhost:9091/api/v1/query --data-urlencode 'query=up' || echo "Failed to query Prometheus"

      - name: Stop and remove Prometheus container
        run: |
          docker stop prometheus
          docker rm prometheus
