name: Delivery Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Pull API image from Docker Hub
      run: |
        docker pull jf202107309/lab03_bd-ii_prometheus:latest

    - name: Start API container
      run: |
        docker run -d --name api_dockerhub_clientes -p 5001:8080 \
          -e ConnectionStrings__ClienteDB=Server=bd_clientes;Database=BD_CLIENTES;User Id=admin_user;Password=UPT.2024;TrustServerCertificate=true \
          jf202107309/lab03_bd-ii_prometheus:latest

    - name: Start Prometheus container
      run: |
        docker run -d --name prometheus_container -p 9090:9090 \
          -v ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro \
          prom/prometheus

    - name: Wait for Prometheus to be ready
      run: |
        echo "Waiting for Prometheus to be available..."
        until $(curl --output /dev/null --silent --head --fail http://host.docker.internal:9090/); do
            printf '.'
            sleep 5
        done
        echo "Prometheus is up and running."

    - name: Get metrics from Prometheus
      run: |
        METRIC_NAME="healthcheck_status"
        RESPONSE=$(curl -s "http://host.docker.internal:9090/api/v1/query?query=$METRIC_NAME")
        echo "Response from Prometheus:"
        echo $RESPONSE

    - name: Stop Docker containers
      run: |
        docker stop api_dockerhub_clientes prometheus_container
        docker rm api_dockerhub_clientes prometheus_container
