name: Delivery Workflow

on:
  workflow_dispatch: # Activado manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull jf202107309/lab03_bd-ii_prometheus:latest

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for the API to be ready
        run: |
          echo "Waiting for API to start..."
          sleep 30  # Esperar a que el contenedor esté listo (ajusta según sea necesario)

      - name: Get metrics from Prometheus
        run: |
          curl -G http://localhost:9090/api/v1/query --data-urlencode 'query=healthcheck_status'
