name: Delivery Workflow

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker images
        run: |
          docker pull jf202107309/lab03_bd-ii_prometheus:latest

      - name: Clean up any existing containers
        run: |
          docker container prune -f

      - name: Run Prometheus container
        run: |
          docker run -d --name prometheus -p 9091:9090 jf202107309/lab03_bd-ii_prometheus:latest

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5000/swagger; then
              echo "API is ready."
              break
            else
              echo "Waiting for API to be ready... (attempt $i)"
              sleep 5
            fi
          done

      - name: Check Prometheus status
        run: |
          for i in {1..45}; do  
            if curl -fs http://localhost:9091/-/healthy; then
              echo "Prometheus is healthy."
              break
            else
              echo "Waiting for Prometheus to be healthy... (attempt $i)"
              sleep 5
            fi
          done

      - name: Make GET request to Prometheus
        run: |
          curl -G http://localhost:9091/api/v1/query --data-urlencode 'query=up' || echo "Failed to query Prometheus"
