name: Delivery Workflow

on:
  workflow_dispatch: # Activado manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Pull Docker image
        run: |
          docker pull jf202107309/lab03_bd-ii_prometheus:latest

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for API to be ready..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:5000/metrics); do
            printf '.'
            sleep 5
          done
          echo "API is ready!"

      - name: Query Prometheus for metrics
        run: |
          response=$(curl -G 'http://localhost:9090/api/v1/query' --data-urlencode 'query=datos_climaticos_temperatura_media')
          echo "Prometheus response: $response"
