name: Delivery Workflow

on:
  workflow_dispatch: # Permite activar el workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Pull Docker image from Docker Hub
      run: |
        # Descargar la imagen desde Docker Hub
        docker pull jf202107309/lab03_bd-ii_prometheus:latest

    - name: Start Docker container
      run: |
        # Iniciar el contenedor usando la imagen descargada
        docker run -d --name prometheus -p 9090:9090 jf202107309/lab03_bd-ii_prometheus:latest

    - name: Wait for Prometheus to be ready
      run: |
        # Esperar a que Prometheus esté disponible
        echo "Waiting for Prometheus to be available..."
        until $(curl --output /dev/null --silent --head --fail http://localhost:9090); do
            printf '.'
            sleep 5
        done
        echo "Prometheus is up and running."

    - name: Get metrics from Prometheus
      run: |
        # Realizar una petición GET a Prometheus para obtener una métrica específica
        METRIC_NAME="healthcheck_status"
        RESPONSE=$(curl -s "http://localhost:9090/api/v1/query?query=$METRIC_NAME")
        echo "Response from Prometheus:"
        echo $RESPONSE

    - name: Stop Docker container
      run: |
        # Detener y eliminar el contenedor después de obtener la métrica
        docker stop prometheus
        docker rm prometheus
