name: Delivery Workflow

on:
  workflow_dispatch: # Activado manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull jf202107309/lab03_bd-ii_prometheus:latest

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Check health status of localhost:5000
        run: |
          echo "Checking health status of localhost:5000..."
          for i in {1..20}; do
            sleep 30  # Esperar 30 segundos antes de reintentar
            health_check_response=$(curl -s -G http://localhost:5000/api/v1/query --data-urlencode 'query=healthcheck_status')
            echo "Health check response: $health_check_response"

            if [[ $health_check_response == *'"value":[*1*' ]]; then
                echo "Health status is 1 (healthy)."
                break
            else
                echo "Health status is not 1 (not healthy). Retrying..."
            fi
            
            if [ $i -eq 20 ]; then
                echo "Failed to get a healthy status after 20 attempts."
                exit 1
            fi
          done
